name: ci

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Display version
        run: |
          python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: | 
          pip install .
          python -m pip install --upgrade pip
          pip install -e .[ci_depends]
      - name: Running tests
        run: |
          pytest tests/
      - name: Isort
        run: |
          isort src/ tests/ --check-only
      - name: Mypy
        run: |
          mypy src/
      - name: Black
        run: |
          black src/ tests/ --check

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
